trigger:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

timeout: "30" # minutes
machine: "L4"
image: "pytorchlightning/lightning-thunder:ubuntu24.04-cuda12.6.3-cudnn-fe1.10.0-py3.10-pt_2.8.0-dev"
parametrize:
  matrix:
      tests:
        - test_transformer_engine_executor.py
        - test_transformer_engine_v2_executor.py

run: |
  whereis nvidia
  nvidia-smi
  pip list
  set -ex

  conda install -c conda-forge libstdcxx-ng
  pip install . -U -q -r requirements/test.txt
  pip install --no-build-isolation 'transformer_engine[pytorch]'
  pip list # for debugging purposes
  pytest tests/${tests} -v -rs
