name: Run Model Coverage Test

on:
  workflow_dispatch: {}


jobs:
  coverage-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -U pip
          pip install torch transformers lightning_sdk
          pip install .

      - name: Run Coverage Trace Test
        run: |
          python thunder/tests/coverage_trace.py